[package]
name = "gfycat_uploader"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[dependencies]
env_logger = "0.5"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
failure = "0.1"