[package]
name = "gfycat_uploader"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[dependencies]
hyper = "0.10"
error-chain = "0.10"
serde = "1"
serde_json = "1"
serde_derive = "1"
multipart = "0.13.1"
env_logger = "*"
clap = "2"
hyper-native-tls = "*"